name: retrofit_xml_sample_app
description: A sample application that uses Retrofit for reading XML api requests.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  retrofit: ^1.3.4
  xml: ^3.5.0
  xml2json: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.3.7
  build_runner: ^1.10.0

flutter:
  uses-material-design: true
